---
driver:
  name: vagrant

  #Amazon tesing instance CUMULUS 
  #name: ec2
  #aws_ssh_key_id: testkey
  #ssh_key: /Users/knietzie/.ssh/testkey.pem
  #region: ap-southeast-1
  #availability_zone: ap-southeast-1a
  #require_chef_omnibus: true

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

  ## amazon instance connection
  #- name: amazon
  #  driver:
  #    image_id: ami-acd9e8fe
  #    username: ec2-user

suites:
  - name: default
    run_list:
      - recipe[ops-web-python::default]
    attributes:



# --- 
# driver:
#   name: ec2
#   aws_ssh_key_id: testkey
#   ssh_key: /Users/knietzie/.ssh/testkey.pem
#   region: ap-southeast-1
#   availability_zone: ap-southeast-1a
#   require_chef_omnibus: true
# provisioner:
#   name: chef_solo
# platforms:
#   - name: amazon
#     driver:
#       image_id: ami-ed8e9284
#       username: ec2-user

# CUMULUS details
#    ######  OpsWorks Summary  ######
#    Operating System: Amazon Linux AMI release 2014.09
#    OpsWorks Instance: cumulus
#    OpsWorks Instance ID: 5264f7bc-0c24-46b9-901b-6ce31c4f6723
#    OpsWorks Layers: Python
#    OpsWorks Stack: OpsTEST
#    EC2 Region: ap-southeast-1
#    EC2 Availability Zone: ap-southeast-1a
#    EC2 Instance ID: i-c7be7c63
#    Public IP: 54.255.233.6
#    Private IP: 172.31.12.244
#    VPC ID: vpc-8e42adeb
#    Subnet ID: subnet-6dba4008

